### ISSUE TITLE
Mithril

### ISSUE THREAD

**Issue by lroal** [bencompton/framework7-react#10]
Have you considered creating for mithriljs also ?
I could try to port your react code to mithril myself though..

How up-to-date and stable is framework7-react now ?

**Comment by bencompton** [comment]
The plan is to merge #9 and release the latest version to NPM early next week. At that point, the React version will have all of the same components as the Vue version and I would consider it beta quality software at that point. Official docs should be going up on framework7.io soon too.

With #9, all of the React components are auto-generated from the Framework7 Vue components, since React and Vue are very similar. It might be possible to take the same approach with mithril as well.

**Comment by lroal** [comment]
Thank you for your quick reply. I really look forward to seeing the official docs when they are ready.

**Comment by lroal** [comment]
Do you have any personal interest in writing a Mithril version. Or would you like others to do that (like me, I am beginner both in mithril and react/vue) ?

**Comment by bencompton** [comment]
Mithril looks interesting, but I have a fair amount to keep me busy already. If you wanted to try your hand at a mithril version, you might be able to leverage some in code in #9. Mithril has the equivalent of a createElement function, so it should work just fine in theory.
