### ISSUE TITLE
Kitchen Sink build does not work

### ISSUE THREAD

**Issue by dburdick** [bencompton/framework7-react#13]
First off, great project, I hope it gets to a solid production level release. Let me know if you'd like some help with that. 

I was trying to test it out and was not able to get the kitchen sink to run. 
```
npm install
gulp
```
lead to the attached error.
[err.txt](https://github.com/bencompton/framework7-react/files/777788/err.txt)

**Comment by bencompton** [comment]
Hi, thanks for the error report. I haven't gotten around to writing all of docs yet for building the app / kitchen sink, but it is also necessary to run `typings install` since this project uses TypeScript:

To build the framework itself:

```javascript
npm install
typings install
gulp
```

To build the kitchen sink:

```javascript
cd kitchen-sink
npm install
typings install
gulp
```

Here's a shortcut for building both after the above two steps have already been completed at least once:

```javascript
npm run build
```

**Comment by bencompton** [comment]
Let me know how that works for you and if there were any additional issues you ran into getting the kitchen sink up and running. I will put these instructions on the README so that others won't run into the same issues you did.

**Comment by bencompton** [comment]
@dburdick - running `typings install` should have fixed your issue, and I updated the README with build instructions (since that's not exactly an obvious step for anyone who doesn't use TypeScript). Let me know if it is still not working for you or if you have any additional feedback. Otherwise, can we close this issue?
