### ISSUE TITLE
Nothing renders on the Browser

### ISSUE THREAD

**Issue by bvodola** [bencompton/framework7-react#18]
Hello, Ben.

I'm trying to create a example/skeleton project using the Meteor+React+F7 stack. I got some of the code from your example project.

When I run the project, nothing renders on the browser. I've had a similar issue when I was running F7+Vue and I solved by setting the F7 root parameter correctly. I've tried the same by writing `<Framework7App themeType="material" routes={Routes} root="#root">`. The root indeed changed, but it didn't solve the issue.

When I inspect the code, the elements are there on the source code, but nothing shows on the screen. Could you maybe advise? The code I've got so far is in here:
https://github.com/bvodola/meteor-react-f7-skel

Thanks!

**Comment by bencompton** [comment]
Hey Brunno - cool template you're building there! I suspect the issue is that the id "root" is already taken by the `Framework7App` component's rendered element. If you change the id in your div tag to something else and specify that as your root instead, that might fix your issue.

**Comment by bencompton** [comment]
Whoops, that's actually not correct. In the example project, the index.html file has an element with an id of root, and that's where I was testing (meteor didn't want to install). Framework7App's rendered element actually has no id, and your project doesn't appear to have any other elements with that id, so that wouldn't be your issue.

I will hopefully have more time later to diagnose why Meteor isn't installing correctly on my machine, but maybe you can check your DOM and see if you have any additional parent elements? Your issue probably has something to do with additional elements being added somewhere. Framework7 is pretty particular about how your app is nested. I have found that when I need to introduce additional nesting elements, I have to use something inert like a span (which I mostly do just to get around React's requirement that every element have a single root element).

**Comment by bvodola** [comment]
Good news: I've made it work. Here's what I did:
- Removed the root prop from the ``Framework7App`` component, thus letting the F7 root to be the ``<body>`` element.
- Changed the entry html element used by react to a ``<span>``. Apparently that makes a difference.

Also, I changed the repo name a bit, so this is the new URL for it:
https://github.com/bvodola/meteor-react-f7-template
Thanks!
