### ISSUE TITLE
Typings vs @types npm packages

### ISSUE THREAD

**Issue by thiagoabreu** [bencompton/framework7-react#20]
Hi. Nice work bringing framework7 to react.

I was wondering, why stick with the "typings" package when the .d.ts files can be installed as dependencies via npm?

i.e. instead of have a "typings.json" file, use the "package.json" file with the following:

```
"devDependencies": {
    "@types/react": "^15.0.12",
    "@types/camelcase": "^0.0.30",
... //other deps
}
```

I mean, it's a build step less.

I can make a PR if you want.

**Comment by bencompton** [comment]
Yeah, that's a great point--thanks for creating an issue! This project has been using TypeScript since 1.8, and you're right that Typings is pretty much obsolete now and the build process would be so much simpler without it.

It's a quick change, so I'll see if I can get around to removing Typings later today.

**Comment by bencompton** [comment]
Okay, Typings is no longer required. Great improvement--I never was a big fan of Typings anyhow. :+1:
