### ISSUE TITLE
setting View url prop - href's stop working on all the Links components

### ISSUE THREAD

**Issue by satyavrat** [bencompton/framework7-react#37]
my MainView looks like this
`<Views layout="white" theme="black">
          <View main url="/">
            <Pages>
              {this.props.appLoader && <AppLoader/>}
            </Pages>
          </View>
        </Views>
`
  
as soon as i remove the url prop, things start working perfectly, but i'm using the url prop to determine the initial landing state (logged in / logged out). 

has anyone else experienced this? or is there another way to achieve this?

My App looks like this:
`
 <Provider store={store}>
      <Framework7App
        pushState
        pushStateSeparator="#page"
        themeType="ios"
        routes={routes}
        stateKernel={framework7StateKernel}
        onFramework7Init={f7 => framework7 = f7}
        onRouteChange={route => currentRoute = route}
      >
        <Sidebar />
        <MainViews />
        <AppPopup />
      </Framework7App>
    </Provider>
`

**Comment by bencompton** [comment]
If I understand correctly, you have something like this in your components `<Link href="..." ... />` and your navigation stops working when you add a url prop to Framework7App? 

If so, it looks like you're using F7 Redux, and a primary goal of F7 Redux is to move the navigation logic to your state management code so your components can simply render data passed in as props and call event handlers passed in as props. So, instead of having `href` properties on your links, you instead should have something like `<Link onClick={this.props.onAboutClicked} />` where your container wires your event props to an action. In addition, your Framework7App component should also have `router={false}` to disable the default Framework7 routing behavior (since Framework7 Redux replaces it with its own routing behavior).

Hope that helps, and sorry if I am misunderstanding what you are asking.

**Comment by satyavrat** [comment]
Yes thats correct, I have a url prop added to Framework 7 <View />(mainview) component, href's on my Link components stopped working after adding the url prop.

Moving to f7redux navigation worked perfectly (y). (for initial cases)
But that brings me to another question - is it a _requirement_ to remove all the href's and replace with f7redux navigation when using redux?

If so, then I have a case which breaks the current flow with having redux controlling the navigation and passing router=false prop in f7 app, that is:

1. I have a social login redirection happening which was handled by router  - my LoginSuccess used to get mounted on success _redirection_, but in this case i'l have to manually check for the hash in url and construct my url prop in the main view (this had its own issue, but will save that for later)

2. So i decided to infer my initial url based on the multiple states I have(logged out, logged in, social redirection success/failure) but once this happened, I could see my initial components mounted twice. which leads to other problems.

Does f7react + redux  support external redirection?
If so then whats the best possible way to handle that?


I might be missing something very trivial as fix, i hope I was able to explain the flow of things!

**Comment by satyavrat** [comment]
Ok so I tried to remove f7redux and used plain f7+react - but even with that configuration when i pass a url prop to view, the href's stop working


my **PRIMARY** issue is:
Once the redirection happens I of open a success page(by checking the url hash) and then try to navigate to another page -> but seems that new page is mounted behind my success page (by behind I mean order of '.page'  elements in dom).

tried without f7redux and with f7redux

**Comment by bencompton** [comment]
> ...is it a requirement to remove all the href's and replace with f7redux navigation when using f7redux

In short, yes. The ability to handle navigation and modals (and potentially other "global" concerns in the future) in Redux instead of in your components is the whole point of F7 Redux. It is similar in purpose to react-router-redux. You can still use Redux without F7 Redux, and in that case, you would handle your navigation in the default Framework7 way with links with hrefs, and other parts of your state (aside from navigation and modals) could still be bound to your components and updated via actions. It is more or less for people who want to be Redux purists. I have it on my todo list still to create examples / starter templates for F7 Redux, so I'm sure that will help ease the pain of getting started in the future.

As for your other issue, it sounds like your app has some workflows that do not require logging in and also has other workflows that do require logging in? Basically, you want to be able to redirect from your app to an external (server rendered I assume) login page? The way I typically accomplish external redirection like that is with `window.location.href = 'external url'` in an action. That's the simple way to do it. If you're trying to do more of an isomorphic style app with React rendering on the server, I won't say that it is not possible with the router in F7 React, but you would be going into uncharted territory.

In my own app, I am doing something pretty similar where there is a server-rendered login page (ASP.NET MVC). After logging in, it redirects to a single-page F7 React + Redux app, and upon loading, the app then immediately calls an action to call the API to get the user session, which then updates the store with the user info and then calls another action that calls into F7 Redux to navigate to the correct route (the app home screen). You could do something similar. If your API says the user is logged in (e.g., the user has a cookie that the login process set or whatever), then your action would navigate to one place, and if not logged in, then it would redirect to another place. Also, when my app first loads, I show a loading screen with a loading spinner, and it isn't until the user session comes back from the API that the app actually navigates anywhere useful.

Perhaps the same approach would work for you. If not, I would probably have to see a fiddle or something reproducing your current issue to be of much further help.
